#include "a90_changelog.h"

#define ENTRY(label, summary, d1, d2, d3, d4, d5) \
    { label, summary, { d1, d2, d3, d4, d5 } }

static const struct a90_changelog_entry changelog_entries[] = {
    ENTRY("0.9.29 v129", "CHANGELOG PAGING",
          "0.9.29 v129 CHANGELOG PAGING",
          "Shares changelog list data",
          "Adds ABOUT page navigation",
          "Keeps button UX stable",
          "Prepares long history growth"),
    ENTRY("0.9.28 v128", "MENU SUBCOMMAND POLICY",
          "Keeps v127 busy-gate mitigation",
          "Allows read-only subcommands",
          "Blocks mutation while menu visible",
          "Adds subcommand-aware controller API",
          NULL),
    ENTRY("0.9.27 v127", "MENU BUSY GATE",
          "Closes F023 busy-gate gap",
          "Uses deny-by-default menu policy",
          "Allows observation commands only",
          "Blocks run/write/mount/mknod paths",
          NULL),
    ENTRY("0.9.26 v126", "SECURITY BATCH6",
          "Keeps retained-source compatibility",
          "Fixes v84 changelog route",
          "Restores v42 run stdin behavior",
          "Adds strict input event validation",
          NULL),
    ENTRY("0.9.25 v125", "SECURITY BATCH4",
          "Uses owner-only diagnostics/logs",
          "Adds private emergency log fallback",
          "Makes HUD log tail opt-in",
          "Reduces passive display leakage",
          NULL),
    ENTRY("0.9.24 v124", "SECURITY BATCH2",
          "Verifies runtime helper SHA-256",
          "Adds no-follow storage/log writes",
          "Adds mountsd SD identity gate",
          "Makes tcpctl install fail closed",
          NULL),
    ENTRY("0.9.23 v123", "SECURITY BATCH1",
          "Requires tcpctl token auth",
          "Binds tcpctl to NCM device IP",
          "Moves tcpctl helper to ramdisk",
          "Marks service mutation dangerous",
          NULL),
    ENTRY("0.9.22 v122", "WIFI REFRESH",
          "Adds wifiinv refresh summary",
          "Adds wififeas refresh summary",
          "Compares v103/v104 baselines",
          "Keeps Wi-Fi bring-up blocked",
          NULL),
    ENTRY("0.9.21 v121", "PID1 GUARD",
          "Adds a90_pid1_guard.c/h",
          "Adds pid1guard shell command",
          "Adds status/bootstatus summary",
          "Runs guard during boot splash",
          NULL),
    ENTRY("0.9.20 v120", "COMMAND GROUP API",
          "Adds command group enum",
          "Adds command table metadata",
          "Adds cmdgroups inventory command",
          "Keeps command handlers in place",
          NULL),
    ENTRY("0.9.19 v119", "MENU ROUTE API",
          "Adds menu action route helper",
          "Removes long changelog case block",
          "Fixes top changelog app category",
          "Preserves screenmenu behavior",
          NULL),
    ENTRY("0.9.18 v118", "SHELL META API",
          "Adds shell metadata helpers",
          "Adds cmdmeta command inventory",
          "Formats command flags consistently",
          "Keeps dispatch logic stable",
          NULL),
    ENTRY("0.9.17 v117", "PID1 SLIM ROADMAP",
          "Records v117-v122 guardrails",
          "Sets PID1 slim roadmap baseline",
          "Keeps verified boot path stable",
          "Prepares Wi-Fi refresh phase",
          NULL),
    ENTRY("0.9.16 v116", "DIAG BUNDLE 2",
          "Extends diagnostics evidence",
          "Captures runtime/helper/service state",
          "Adds network and rshell evidence",
          "Improves host bundle collection",
          NULL),
    ENTRY("0.9.15 v115", "RSHELL HARDENING",
          "Adds rshell audit view",
          "Uses 0600 token state",
          "Rejects invalid tokens",
          "Validates NCM smoke rollback",
          NULL),
    ENTRY("0.9.14 v114", "HELPER DEPLOY 2",
          "Improves helper deployment visibility",
          "Records manifest and plan paths",
          "Keeps runtime helper fallback",
          "Adds deploy log evidence",
          NULL),
    ENTRY("0.9.13 v113", "RUNTIME PACKAGE LAYOUT",
          "Defines package-friendly runtime paths",
          "Documents helper manifest contract",
          "Keeps SD/cache fallback behavior",
          "Prepares userland packaging",
          NULL),
    ENTRY("0.9.12 v112", "USB SERVICE SOAK",
          "Runs opt-in NCM/tcpctl soak",
          "Verifies host ping/TCP control",
          "Checks ACM rollback",
          "Confirms USB service recovery",
          NULL),
    ENTRY("0.9.11 v111", "EXTENDED SOAK RC",
          "Runs 10-cycle host soak",
          "Checks final service state",
          "Checks final selftest state",
          "Preserves recovery-friendly baseline",
          NULL),
    ENTRY("0.9.10 v110", "APP CONTROLLER CLEANUP",
          "Moves auto-menu IPC helpers",
          "Centralizes menu state policy",
          "Keeps app routing behavior",
          "Prepares shell/controller split",
          NULL),
    ENTRY("0.9.9 v109", "STRUCTURE AUDIT 2",
          "Audits post-v108 boundaries",
          "Records next cleanup targets",
          "Keeps verified source layout",
          "No user-visible feature change",
          NULL),
    ENTRY("0.9.8 v108", "APP INPUTMON API",
          "Splits input monitor app",
          "Keeps raw/gesture trace UI",
          "Preserves button regression tests",
          "Completes UI app split cycle",
          NULL),
    ENTRY("0.9.7 v107", "APP DISPLAYTEST API",
          "Splits display test app",
          "Keeps colors/font/safe pages",
          "Keeps cutout calibration path",
          "Preserves visual regression tests",
          NULL),
    ENTRY("0.9.6 v106", "APP ABOUT API",
          "Splits ABOUT app renderer",
          "Adds a90_app_about.c/h",
          "Moves version/changelog screens",
          "Keeps app controller stable",
          NULL),
    ENTRY("0.9.5 v105", "SOAK RC",
          "Adds native soak validator",
          "Runs recovery-friendly baseline",
          "Keeps Wi-Fi active bring-up blocked",
          "Completes v96-v105 long plan",
          NULL),
    ENTRY("0.9.4 v104", "WIFI FEASIBILITY",
          "Adds Wi-Fi feasibility gate",
          "Compares current evidence",
          "Keeps bring-up no-go by default",
          "Documents missing kernel-facing gates",
          NULL),
    ENTRY("0.9.3 v103", "WIFI INVENTORY",
          "Adds read-only WLAN inventory",
          "Captures firmware/rfkill paths",
          "Avoids active Wi-Fi mutation",
          "Builds baseline evidence",
          NULL),
    ENTRY("0.9.2 v102", "DIAGNOSTICS",
          "Adds diagnostics module",
          "Adds host diag collection",
          "Collects read-only evidence",
          "Improves troubleshooting bundle",
          NULL),
    ENTRY("0.9.1 v101", "SERVICE MANAGER",
          "Adds service command view",
          "Tracks autohud/tcpctl/adbd/rshell",
          "Adds common service metadata",
          "Preserves manual controls",
          NULL),
    ENTRY("0.9.0 v100", "REMOTE SHELL",
          "Adds token-auth TCP rshell",
          "Runs over USB NCM",
          "Adds host smoke helper",
          "Keeps disabled unless started",
          NULL),
    ENTRY("0.8.29 v98", "HELPER DEPLOY",
          "Adds helper inventory",
          "Tracks preferred/fallback helpers",
          "Documents manifest path",
          "Keeps ramdisk helper fallback",
          NULL),
    ENTRY("0.8.28 v97", "SD RUNTIME ROOT",
          "Adds SD runtime root contract",
          "Keeps cache fallback",
          "Creates runtime directory layout",
          "Adds runtime command",
          NULL),
    ENTRY("0.8.27 v96", "STRUCTURE AUDIT",
          "Audits v95 module boundaries",
          "Fixes stale console markers",
          "Records cleanup plan",
          "No user-visible feature change",
          NULL),
    ENTRY("0.8.26 v95", "NETSERVICE USB API",
          "Splits USB gadget helpers",
          "Splits netservice policy",
          "Preserves ACM/NCM UX",
          "Keeps tcpctl helper path",
          NULL),
    ENTRY("0.8.25 v94", "BOOT SELFTEST",
          "Adds boot selftest API",
          "Runs non-destructive checks",
          "Surfaces pass/warn/fail summary",
          "Keeps boot warn-only",
          NULL),
    ENTRY("0.8.24 v93", "STORAGE API",
          "Splits storage API",
          "Tracks SD/cache backend",
          "Preserves mountsd command",
          "Keeps critical partition guardrails",
          NULL),
    ENTRY("0.8.23 v92", "SHELL CONTROLLER",
          "Splits shell metadata",
          "Splits controller policy",
          "Keeps command handlers in tree",
          "Preserves screenmenu behavior",
          NULL),
    ENTRY("0.8.22 v91", "CPUSTRESS HELPER",
          "Moves CPU stress outside PID1",
          "Adds static helper process",
          "Uses run API cancellation",
          "Keeps menu stress UX",
          NULL),
    ENTRY("0.8.21 v90", "METRICS API",
          "Splits metrics snapshot API",
          "Moves battery/CPU/GPU/MEM reads",
          "Keeps HUD display behavior",
          "Preserves stress telemetry",
          NULL),
    ENTRY("0.8.20 v89", "MENU CONTROL API",
          "Splits menu model/state",
          "Makes screenmenu nonblocking",
          "Keeps blindmenu foreground rescue",
          "Preserves app routing",
          NULL),
    ENTRY("0.8.19 v88", "HUD API",
          "Splits HUD renderer",
          "Moves boot splash/log tail drawing",
          "Keeps display/menu UX",
          "Prepares menu split",
          NULL),
    ENTRY("0.8.18 v87", "INPUT API",
          "Splits physical input API",
          "Moves gesture decoder",
          "Keeps button menu actions",
          "Improves boot summary time",
          NULL),
    ENTRY("0.8.17 v86", "KMS DRAW API",
          "Splits KMS framebuffer API",
          "Splits draw primitives",
          "Keeps HUD/menu logic",
          "Preserves display tests",
          NULL),
    ENTRY("0.8.16 v85", "RUN SERVICE API",
          "Splits run/service lifecycle",
          "Tracks service PIDs centrally",
          "Reduces zombie/stale PID risk",
          "Keeps command UX",
          NULL),
    ENTRY("0.8.15 v84", "CMDPROTO API",
          "Splits cmdv1/cmdv1x protocol",
          "Keeps shell dispatch in tree",
          "Preserves framed host result",
          "Keeps raw reboot controls",
          NULL),
    ENTRY("0.8.14 v83", "CONSOLE API",
          "Splits console fd handling",
          "Moves attach/readline/cancel",
          "Hides raw console fd",
          "Preserves serial bridge UX",
          NULL),
    ENTRY("0.8.13 v82", "LOG TIMELINE API",
          "Splits log module",
          "Splits boot timeline module",
          "Preserves logpath/timeline commands",
          "Keeps SD/cache log fallback",
          NULL),
    ENTRY("0.8.12 v81", "CONFIG UTIL API",
          "Splits config/util base",
          "Keeps PID1 single binary",
          "Prepares module boundaries",
          "No user-visible feature change",
          NULL),
    ENTRY("0.8.11 v80", "SOURCE MODULES",
          "Splits PID1 source includes",
          "Keeps one static init binary",
          "Improves source navigation",
          "Prepares compiled modules",
          NULL),
    ENTRY("0.8.10 v79", "BOOT SD PROBE",
          "Adds SD boot health check",
          "Uses SD runtime when healthy",
          "Falls back to cache when needed",
          "Shows storage warning",
          NULL),
    ENTRY("0.8.9 v78", "SD WORKSPACE",
          "Adds ext4 SD workspace",
          "Adds mountsd command",
          "Keeps cache fallback",
          "Avoids main storage experiments",
          NULL),
    ENTRY("0.8.8 v77", "DISPLAY TEST PAGES",
          "Splits display test pages",
          "Adds color/font/safe previews",
          "Adds cutout calibration",
          "Improves visual testing",
          NULL),
    ENTRY("0.8.7 v76", "AT FRAGMENT FILTER",
          "Filters serial AT fragments",
          "Reduces unknown command noise",
          "Keeps shell command behavior",
          "Improves bridge readability",
          NULL),
    ENTRY("0.8.6 v75", "QUIET IDLE REATTACH",
          "Suppresses idle reattach spam",
          "Keeps requested reattach logs",
          "Improves HUD log tail signal",
          "Preserves serial recovery",
          NULL),
    ENTRY("0.8.5 v74", "CMDV1 ARG ENCODING",
          "Adds cmdv1x argv encoding",
          "Supports whitespace arguments",
          "Keeps cmdv1 compatibility",
          "Improves host wrapper safety",
          NULL),
    ENTRY("0.8.4 v73", "CMDV1 PROTOCOL",
          "Adds A90P1 framed results",
          "Reports rc/status/duration",
          "Improves host verification",
          "Keeps raw commands available",
          NULL),
    ENTRY("0.8.3 v72", "DISPLAY TEST FIX",
          "Fixes display test rendering",
          "Keeps safe-area calibration",
          "Improves screen validation",
          "Preserves menu navigation",
          NULL),
    ENTRY("0.8.2 v71", "MENU LOG TAIL",
          "Adds menu live log tail",
          "Uses empty screen space",
          "Keeps status HUD visible",
          "Improves operator feedback",
          NULL),
    ENTRY("0.8.1 v70", "INPUT MONITOR APP",
          "Adds input monitor app",
          "Shows raw/gesture traces",
          "Helps button mapping debug",
          "Preserves menu actions",
          NULL),
    ENTRY("0.8.0 v69", "INPUT GESTURE LAYOUT",
          "Adds gesture layout",
          "Maps single/double/long/combo",
          "Improves physical-button UX",
          "Keeps no-touch operation",
          NULL),
    ENTRY("0.7.5 v68", "LOG TAIL + HISTORY",
          "Adds HUD log tail history",
          "Expands changelog history",
          "Improves ABOUT visibility",
          "Preserves menu structure",
          NULL),
    ENTRY("0.7.4 v67", "DETAIL CHANGELOG UI",
          "Reduces ABOUT text scale",
          "Opens changelog version list",
          "Adds version detail screens",
          "Improves credits screen",
          NULL),
    ENTRY("0.7.3 v66", "ABOUT + VERSIONING",
          "Adds semantic version display",
          "Adds made-by credit",
          "Adds ABOUT folder",
          "Adds versioning docs",
          NULL),
    ENTRY("0.7.2 v65", "SPLASH SAFE LAYOUT",
          "Adds splash safe layout",
          "Avoids clipped footer text",
          "Improves notch/punch-hole fit",
          "Keeps boot transition",
          NULL),
    ENTRY("0.7.1 v64", "CUSTOM BOOT SPLASH",
          "Adds A90 native init splash",
          "Replaces TEST boot pattern",
          "Keeps HUD transition",
          "Improves boot identity",
          NULL),
    ENTRY("0.7.0 v63", "APP MENU",
          "Adds hierarchical app menu",
          "Adds CPU stress app",
          "Uses physical buttons",
          "Keeps status HUD",
          NULL),
    ENTRY("0.6.0 v62", "CPU DIAGNOSTICS",
          "Adds CPU stress diagnostics",
          "Shows CPU status details",
          "Adds dev node guards",
          "Improves runtime testing",
          NULL),
    ENTRY("0.5.1 v61", "CPU/GPU USAGE HUD",
          "Adds CPU/GPU usage percent",
          "Shows thermal metrics",
          "Improves HUD telemetry",
          "Validates with stress load",
          NULL),
    ENTRY("0.5.0 v60", "NETSERVICE BOOT",
          "Adds opt-in boot netservice",
          "Starts NCM/tcpctl by flag",
          "Validates reconnect recovery",
          "Keeps default disabled",
          NULL),
    ENTRY("0.4.1 v59", "AT SERIAL FILTER",
          "Ignores modem AT probes",
          "Reduces serial noise",
          "Keeps console usable",
          "Improves bridge sessions",
          NULL),
    ENTRY("0.4.0 v55", "NCM TCP CONTROL",
          "Adds USB NCM operations",
          "Adds TCP nettest helper",
          "Validates bidirectional payload",
          "Builds network control path",
          NULL),
    ENTRY("0.3.0 v53", "MENU BUSY GATE",
          "Adds first menu busy policy",
          "Protects foreground menu control",
          "Keeps serial hide command",
          "Improves UI safety",
          NULL),
    ENTRY("0.2.0 v40", "SHELL LOG HUD CORE",
          "Adds shell/log/HUD baseline",
          "Adds boot timeline",
          "Adds run helper path",
          "Improves native init control",
          NULL),
    ENTRY("0.1.0 v1", "NATIVE INIT ORIGIN",
          "Boots custom static init",
          "Runs stock Android kernel",
          "Provides rescue shell",
          "Starts native userspace project",
          NULL),
};

size_t a90_changelog_count(void) {
    return sizeof(changelog_entries) / sizeof(changelog_entries[0]);
}

const struct a90_changelog_entry *a90_changelog_entry_at(size_t index) {
    if (index >= a90_changelog_count()) {
        return NULL;
    }
    return &changelog_entries[index];
}

size_t a90_changelog_detail_count(const struct a90_changelog_entry *entry) {
    size_t count = 0;

    if (entry == NULL) {
        return 0;
    }
    while (count < A90_CHANGELOG_DETAIL_MAX && entry->details[count] != NULL) {
        ++count;
    }
    return count;
}

#undef ENTRY
